### ISSUE TITLE
[BUG] Can't start AppImage in AlmaLinux 8

### ISSUE THREAD

**Issue by gwyn17** [session-foundation/session-desktop#313]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

./session-desktop-linux-x86_64-1.10.8.AppImage 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/config
NODE_CONFIG {}
userData: /home/fil/.config/Session
config/get: Successfully read user config file
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance

(session-desktop-bin:2852605): Gtk-WARNING **: 13:43:23.104: Theme parsing error: gtk.css:490:34: 'font-feature-settings' is not a valid property name

(session-desktop-bin:2852605): Gtk-WARNING **: 13:43:23.112: Theme parsing error: gtk.css:1306:81: 'font-feature-settings' is not a valid property name

(session-desktop-bin:2852605): Gtk-WARNING **: 13:43:23.114: Theme parsing error: gtk.css:1469:82: 'font-feature-settings' is not a valid property name
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":30,"msg":"app ready","time":"2023-06-03T17:43:23.632Z","v":0}
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":30,"msg":"starting version 1.10.8","time":"2023-06-03T17:43:23.633Z","v":0}
initializeSql sqlnode
Made sure db folder exists at: /home/fil/.config/Session/sql
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":30,"msg":"migrateDatabase: Migration without cipher change failed {\"code\":\"ERR_DLOPEN_FAILED\"}","time":"2023-06-03T17:43:23.678Z","v":0}
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":30,"msg":"migrateDatabase: migrateSchemaVersion failed {\"code\":\"ERR_DLOPEN_FAILED\"}","time":"2023-06-03T17:43:23.680Z","v":0}
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":50,"msg":"error {}","time":"2023-06-03T17:43:23.681Z","v":0}
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":30,"msg":"Database startup error: Error: db is not set\n    at Object.initializeSql ([REDACTED]/ts/node/sql.js:93:19)\n    at showMainWindow ([REDACTED]/ts/mains/main_node.js:608:25)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:582:9)","time":"2023-06-03T17:43:23.682Z","v":0}
Gtk-Message: 13:43:23.754: GtkDialog mapped without a transient parent. This is discouraged.
[2852658:0603/134323.768873:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Unhandled Promise Rejection: Error: neither globalInstance nor initialized is initialized.
    at assertGlobalInstanceOrInstance (/home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/ts/node/sql.js:53:15)
    at getById (/home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/ts/node/sql.js:239:17)
    at Object.getItemById (/home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/ts/node/sql.js:208:12)
    at getSpellCheckSetting (/home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/ts/mains/main_node.js:76:32)
    at showMainWindow (/home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/ts/mains/main_node.js:614:46)
    at async App.<anonymous> (/home/fil/tmp/.mount_sessioGOz3F0/resources/app.asar/ts/mains/main_node.js:582:9)
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":50,"msg":"Unhandled Promise Rejection: {}","time":"2023-06-03T17:43:48.518Z","v":0}
Gtk-Message: 13:43:48.580: GtkDialog mapped without a transient parent. This is discouraged.
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":50,"msg":"(node:2852605) UnhandledPromiseRejectionWarning: Error: neither globalInstance nor initialized is initialized.\n    at assertGlobalInstanceOrInstance ([REDACTED]/ts/node/sql.js:53:15)\n    at getById ([REDACTED]/ts/node/sql.js:239:17)\n    at Object.getItemById ([REDACTED]/ts/node/sql.js:208:12)\n    at getSpellCheckSetting ([REDACTED]/ts/mains/main_node.js:76:32)\n    at showMainWindow ([REDACTED]/ts/mains/main_node.js:614:46)\n    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:582:9)\n(Use `session-desktop-bin --trace-warnings ...` to show where the warning was created)","time":"2023-06-03T17:43:48.582Z","v":0}
{"name":"log","hostname":"scott.localdomain","pid":2852605,"level":50,"msg":"(node:2852605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see [REDACTED] (rejection id: 2)","time":"2023-06-03T17:43:48.582Z","v":0}

### Expected Behavior

I expected to launch the app and use session on my AlmaLinux computer

### Steps To Reproduce

1. Download session-desktop-linux-x86_64-1.10.8.AppImage
2. md5sum session-desktop-linux-x86_64-1.10.8.AppImage 
4a4d48f03f9c3ee8f9c713325148dabf  session-desktop-linux-x86_64-1.10.8.AppImage
3. chmod +x session-desktop-linux-x86_64-1.10.8.AppImage 
4. ./session-desktop-linux-x86_64-1.10.8.AppImage 
5. cat /etc/redhat-release 
AlmaLinux release 8.6 (Sky Tiger)

### Desktop Version

1.10.8

**Comment by RubenGarcia** [comment]
I recommend closing this as the operating system is not supported due to too old glibc.
