### ISSUE TITLE
Error db not set

### ISSUE THREAD

**Issue by Dogoj** [session-foundation/session-desktop#344]
Getting this Error when trying to load from desktop

Error: db is not set
    at Object.initializeSql ([REDACTED]\ts\node\sql.js:93:19)
    at showMainWindow ([REDACTED]\ts\mains\main_node.js:608:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async App.<anonymous> ([REDACTED]\ts\mains\main_node.js:582:9)**

then session failed to start please start from terminal 

please help

![Screenshot 2023-04-11 194628](https://user-images.githubusercontent.com/128523207/231259934-63549d02-3a92-4612-bcd3-e11760d6edaf.png)
![Screenshot 2023-04-11 194700](https://user-images.githubusercontent.com/128523207/231259974-03239d0b-f487-41c4-afb2-473960994881.png)

**Comment by Bilb** [comment]
Hey, the error is pretty explicit
```version `GLIBC_2.29' not found (required by [REDACTED].unpacked/node_modules/[...]```

As explained in the Release Notes, the latest release of Session desktop needs
>  a Linux distribution with glibc 2.35 or later like Debian 12 or Ubuntu 22.04
